div_urls:
  england:
    premier_league: 'E0'
    championship: 'E1'

  scotland:
    premier_league: 'SC0'
    division_1: 'SC1'

  germany:
    bundesliga_1: 'D1'
    bundesliga_2: 'D2'

  italy:
    serie_a: 'I1'
    serie_b: 'I2'

  spain:
    li_liga_primera: 'SP1'
    li_liga_segunda: 'SP2'

  france:
    le_championnat: 'F1'
    division_2: 'F2'

  netherlands:
    eredivisie: 'N1'

  belgium:
    jupiler_league: 'B1'

  portugal:
    liga_I: 'P1'

  turkey:
    futbol_ligi_1: 'T1'

  greece:
    ethiniki_katigoria: 'G1'

transfermarkt_team_ids:
  Standard: '3057'
  Charleroi: '172'
  Cercle Brugge: '520'
  Gent: '157'
  Lierse: '28107'
  Oostende: '2861'
  Waasland-Beveren: '49389'
  Club Brugge: '2282'
  Westerlo: '968'
  Lokeren: '7773'
  Anderlecht: '58'
  Mouscron-Peruwelz: '29228'
  Mechelen: '354'
  Genk: '1184'
  Waregem: '3508'
  Kortrijk: '601'
  St Truiden: '475'
  Oud-Heverlee Leuven: '2727'
  Mouscron: '29228'
  Eupen: '1245'
  Beerschot VA: '41274'
  Seraing: '2715'
  St. Gilloise: '3948'
  RWD Molenbeek: '54189'
  Arsenal: '11'
  Crystal Palace: '873'
  Leicester: '1003'
  Everton: '29'
  Man United: '985'
  Swansea: '2288'
  QPR: '1039'
  Hull: '3008'
  Stoke: '512'
  Aston Villa: '405'
  West Brom: '984'
  Sunderland: '289'
  West Ham: '379'
  Tottenham: '148'
  Liverpool: '31'
  Southampton: '180'
  Newcastle: '762'
  Man City: '281'
  Burnley: '1132'
  Chelsea: '631'
  Bournemouth: '989'
  Watford: '1010'
  Norwich: '1123'
  Middlesbrough: '641'
  Brighton: '1237'
  Huddersfield: '1110'
  Cardiff: '603'
  Fulham: '931'
  Wolves: '543'
  Sheffield United: '350'
  Leeds: '399'
  Brentford: '1148'
  Nott'm Forest: '703'
  Luton: '1031'
  Blackburn: '164'
  Charlton: '358'
  Sheffield Weds: '1035'
  Derby: '22'
  Rotherham: '1194'
  Ipswich: '677'
  Millwall: '1028'
  Blackpool: '1181'
  Bolton: '355'
  Wigan: '1071'
  Reading: '1032'
  Milton Keynes Dons: '991'
  Bristol City: '698'
  Preston: '466'
  Barnsley: '349'
  Burton: '2963'
  Wycombe: '2805'
  Coventry: '990'
  Peterboro: '1072'
  Plymouth: '2262'
  Reims: '1421'
  Paris SG: '583'
  Bastia: '595'
  Marseille: '244'
  Evian Thonon Gaillard: '14171'
  Caen: '1162'
  Guingamp: '855'
  St Etienne: '618'
  Lille: '1082'
  Metz: '347'
  Montpellier: '969'
  Bordeaux: '40'
  Nantes: '995'
  Lens: '826'
  Nice: '417'
  Toulouse: '415'
  Lyon: '1041'
  Rennes: '273'
  Monaco: '162'
  Lorient: '1158'
  Angers: '1420'
  Troyes: '1095'
  Ajaccio GFCO: '3558'
  Dijon: '2969'
  Nancy: '1159'
  Strasbourg: '667'
  Amiens: '1416'
  Nimes: '1160'
  Clermont: '3524'
  Ajaccio: '1147'
  Auxerre: '290'
  Le Havre: '738'
  Valenciennes: '1423'
  Arles: '11300'
  Chateauroux: '1175'
  Laval: '1080'
  Niort: '1161'
  Tours: '3161'
  Creteil: '2067'
  Sochaux: '750'
  Orleans: '10868'
  Bourg Peronnas: '2972'
  Paris FC: '10004'
  Red Star: '1154'
  Quevilly Rouen: '7124'
  Grenoble: '1290'
  Beziers: '10867'
  Chambly: '35012'
  Rodez: '11273'
  Le Mans: '1164'
  Dunkerque: '9202'
  Pau FC: '3166'
  Annecy: '30204'
  Concarneau: '21688'
  Bayern Munich: '27'
  Wolfsburg: '82'
  Dortmund: '16'
  Leverkusen: '15'
  Ein Frankfurt: '24'
  Freiburg: '60'
  FC Koln: '3'
  Hamburg: '41'
  Hannover: '42'
  Schalke 04: '33'
  Hertha: '44'
  Werder Bremen: '86'
  Hoffenheim: '533'
  Augsburg: '167'
  M'gladbach: '18'




transfermarkt_team_names:
  Standard: 'standard-luttich'
  Charleroi: 'rsc-charleroi'
  Cercle Brugge: 'cercle-brugge'
  Gent: 'kaa-gent'
  Lierse: 'ksk-lierse-kempenzonen'
  Oostende: 'kv-oostende'
  Waasland-Beveren: 'waasland-beveren-u19'
  Club Brugge: 'fc-brugge'
  Westerlo: 'kvc-westerlo'
  Lokeren: 'ksc-lokeren-temse'
  Anderlecht: 'rsc-anderlecht'
  Mouscron-Peruwelz: 'royal-excel-mouscron'
  Mechelen: 'kv-mechelen'
  Genk: 'krc-genk'
  Waregem: 'sv-zulte-waregem'
  Kortrijk: 'kv-kortrijk'
  St Truiden: 'vv-st-truiden'
  Oud-Heverlee Leuven: 'oud-heverlee-leuven'
  Mouscron: 'royal-excel-mouscron'
  Eupen: 'kas-eupen'
  Beerschot VA: 'beerschot-v-a-'
  Seraing: 'rfc-seraing'
  St. Gilloise: 'royale-union-saint-gilloise'
  RWD Molenbeek: 'rwd-molenbeek'
  Arsenal: 'fc-arsenal'
  Crystal Palace: 'crystal-palace'
  Leicester: 'leicester-city'
  Everton: 'fc-everton'
  Man United: 'manchester-united'
  Swansea: 'swansea-city'
  QPR: 'queens-park-rangers'
  Hull: 'hull-city'
  Stoke: 'stoke-city'
  Aston Villa: 'aston-villa'
  West Brom: 'west-bromwich-albion'
  Sunderland: 'afc-sunderland'
  West Ham: 'west-ham-united'
  Tottenham: 'tottenham-hotspur'
  Liverpool: 'fc-liverpool'
  Southampton: 'fc-southampton'
  Newcastle: 'newcastle-united'
  Man City: 'manchester-city'
  Burnley: 'fc-burnley'
  Chelsea: 'fc-chelsea'
  Bournemouth: 'afc-bournemouth'
  Watford: 'fc-watford'
  Norwich: 'norwich-city'
  Middlesbrough: 'fc-middlesbrough'
  Brighton: 'brighton-amp-hove-albion'
  Huddersfield: 'huddersfield-town'
  Cardiff: 'cardiff-city'
  Fulham: 'fc-fulham'
  Wolves: 'wolverhampton-wanderers'
  Sheffield United: 'sheffield-united'
  Leeds: 'leeds-united'
  Brentford: 'fc-brentford'
  Nott'm Forest: 'nottingham-forest'
  Luton: 'luton-town'
  Blackburn: 'blackburn-rovers'
  Charlton: 'charlton-athletic'
  Sheffield Weds: 'sheffield-wednesday'
  Derby: 'derby-county'
  Rotherham: 'rotherham-united'
  Ipswich: 'ipswich-town'
  Millwall: 'fc-millwall'
  Blackpool: 'fc-blackpool'
  Bolton: 'bolton-wanderers'
  Wigan: 'wigan-athletic'
  Reading: 'fc-reading'
  Milton Keynes Dons: 'milton-keynes-dons'
  Bristol City: 'bristol-city'
  Preston: 'preston-north-end'
  Barnsley: 'fc-barnsley'
  Burton: 'burton-albion'
  Wycombe: 'wycombe-wanderers'
  Coventry: 'coventry-city'
  Peterboro: 'peterborough-united'
  Plymouth: 'plymouth-argyle'
  Reims: 'stade-reims'
  Paris SG: 'fc-paris-saint-germain'
  Bastia: 'sc-bastia'
  Marseille: 'olympique-marseille'
  Evian Thonon Gaillard: 'thonon-evian-grand-geneve-fc'
  Caen: 'sm-caen'
  Guingamp: 'ea-guingamp'
  St Etienne: 'as-saint-etienne'
  Lille: 'losc-lille'
  Metz: 'fc-metz'
  Montpellier: 'montpellier-hsc'
  Bordeaux: 'fc-girondins-bordeaux'
  Nantes: 'fc-nantes'
  Lens: 'rc-lens'
  Nice: 'ogc-nizza'
  Toulouse: 'fc-toulouse'
  Lyon: 'olympique-lyon'
  Rennes: 'fc-stade-rennes'
  Monaco: 'as-monaco'
  Lorient: 'fc-lorient'
  Angers: 'sco-angers'
  Troyes: 'es-troyes-ac'
  Ajaccio GFCO: 'gfc-ajaccio'
  Dijon: 'dijon-fco'
  Nancy: 'as-nancy-lorraine'
  Strasbourg: 'rc-strassburg-alsace'
  Amiens: 'amiens-sc'
  Nimes: 'nimes-olympique'
  Clermont: 'clermont-foot-63'
  Ajaccio: 'ac-ajaccio'
  Auxerre: 'aj-auxerre'
  Le Havre: 'ac-le-havre'
  Valenciennes: 'fc-valenciennes'
  Arles: 'athletic-club-arlesien'
  Chateauroux: 'lb-chateauroux'
  Laval: 'stade-laval'
  Niort: 'chamois-niortais-fc'
  Tours: 'fc-tours'
  Creteil: 'us-creteil-lusitanos'
  Sochaux: 'fc-sochaux-montbeliard'
  Orleans: 'us-orleans'
  Bourg Peronnas: 'bourg-en-bresse-peronnas-01'
  Paris FC: 'paris-fc'
  Red Star: 'red-star-fc'
  Quevilly Rouen: 'quevilly-rouen-metropole'
  Grenoble: 'grenoble-foot-38'
  Beziers: 'as-beziers'
  Chambly: 'fc-chambly'
  Rodez: 'rodez-af'
  Le Mans: 'le-mans-fc'
  Dunkerque: 'usl-dunkerque'
  Pau FC: 'pau-fc'
  Annecy: 'fc-annecy'
  Concarneau: 'us-concarneau'
  Bayern Munich: 'fc-bayern-munchen'
  Wolfsburg: 'vfl-wolfsburg'
  Dortmund: 'borussia-dortmund'
  Leverkusen: 'bayer-04-leverkusen'
  Ein Frankfurt: 'eintracht-frankfurt'
  Freiburg: 'sc-freiburg'
  FC Koln: '1-fc-koln'
  Hamburg: 'hamburger-sv'
  Hannover: 'hannover-96'
  Schalke 04: 'fc-schalke-04'
  Hertha: 'hertha-bsc'
  Werder Bremen: 'sv-werder-bremen'
  Hoffenheim: 'tsg-1899-hoffenheim'
  Augsburg: 'fc-augsburg'
  M'gladbach: 'borussia-monchengladbach'
